Work/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('admin/', admin.site.urls),
]

apps/core/urls.py
from django.urls.conf import include
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.login_view, name='login_view'),
    path('home/', views.home_view, name='home_view'),
    path('profile/', views.user_profile, name="user_profile"),
    path('login/', views.login_view, name="login_view"),
    path('tables/', views.tables_view, name="tables_view"),
    path('register/', views.new_usuario, name='new_usuario'),
    path('logout/', views.logout, name='logout'),
]

apps/core/models.py
import pytz
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin


class EmailUserManager(BaseUserManager):
    def create_user(self, *args, **kwargs):
        email = kwargs["email"]
        email = self.normalize_email(email)
        password = kwargs["password"]
        kwargs.pop("password")

        if not email:
            raise ValueError(_('Necessário um email válido'))

        user = self.model(**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, *args, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class MyUser(PermissionsMixin, AbstractBaseUser):
    first_name = models.CharField(
        verbose_name=_('Nome'), max_length=255, blank=False, help_text=_('Informe seu nome')
    )
    last_name = models.CharField(
        verbose_name=_('Sobrenome'), max_length=255, blank=False, help_text=_('Informe seu sobrenome')
    )
    email = models.EmailField(
        verbose_name=_('Email'), unique=True, max_length=255
    )
    reset_pass = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    objects = EmailUserManager()

    def __str__(self):
        return "{} | {}".format(self.id, self.email)

    def __repr__(self):
        return "{} | {}".format(self.id, self.email)

    @property
    def ativo_human(self):
        return 'Sim' if self.is_active else 'Não'

apps/core/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(
        label='PRIMEIRO NOME:',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    last_name = forms.CharField(
        label='ÚLTIMO NOME:',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    email = forms.CharField(
        label='E-MAIL:',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'maxlength': '100', 'placeholder': 'email@email.com.br', 'type': 'email'}
        )
    )

    telephone = forms.CharField(
        label='TELEFONE:',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '(99) 9999-9999'}
        )
    )

    cell_phone = forms.CharField(
        label='CELULAR:',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '(99) 99999-9999'}
        )
    )

    password1 = forms.CharField(
        label='SENHA:',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Digite a senha'
            }
        )
    )

    password2 = forms.CharField(
        label='CONFIRMAÇÃO DA SENHA:',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control', 'placeholder': 'Digite novamente'
            }
        )
    )

    class Meta:
        model = models.MyUser
        fields = ['first_name', 'last_name', 'email', 'telephone', 'cell_phone', 'password1',
                  'password2']

apps/core/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import logout_then_login
from django.http import FileResponse, HttpResponse, Http404, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.urls import reverse, reverse_lazy


def new_usuario(request):
    if request.user.is_authenticated:
        add = False
        form = forms.CustomUserCreationForm()
        if request.user.is_authenticated:
            if request.method == 'POST':
                form = forms.CustomUserCreationForm(request.POST)
                if form.is_valid():
                    form.save()
                    add = True

        context = {
            'add': add, 'form': form
        }
        return render(request, 'registration/register.html', context)
    return redirect(
        reverse(
            'core:login_view'
        )
    )


def login_view(request):
    invalid = False
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print('helloword')
        if user:
            login(request, user)
            return redirect('core:home_view')
        else:
            invalid = True
    context = {
        'invalid': invalid
    }
    return render(request, 'registration/login.html', context)


def user_profile(request):
    if request.user.is_authenticated:
        print('hello')
        return render(request, 'profile.html')
    return redirect('core:login_view')


def tables_view(request):
    if request.user.is_authenticated:
        return render(request, 'tables.html')
    return redirect('core:login_view')


def home_view(request):
    if request.user.is_authenticated:
        return render(request, 'home.html')
    return redirect('core:login_view')


def logout(request):
    return logout_then_login(request, login_url='/login')

apps/core/templates/index.html
{% extends 'masterpage.html' %}
{% load static %}

{% block title %}Index{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="container">
        {% if form.errors %}
            <div class="row">
                <div class="col">
                    <div class="alert alert-danger">
                        {{ form.errors }}
                    </div>
                </div>
            </div>
        {% endif %}
        {% for f in form %}
            <div class="row">
                <div class="col">
                    {{ f.label }}
                    {{ f }}
                </div>
            </div>
        {% endfor %}
        <br>
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-success btn-lg" type="submit">Cadastrar</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

apps/core/templates/masterpage.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicon -->
    <link href="/static/img/brand/favicon.png" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="/static/js/plugins/nucleo/css/nucleo.css" rel="stylesheet"/>
    <link href="/static/js/plugins/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="/static/css/argon-dashboard.css?v=1.1.1" rel="stylesheet"/>

    <!--   Core   -->
    <script src="/static/js/plugins/jquery/dist/jquery.min.js"></script>
    <script src="/static/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--   Optional JS   -->
    <!--   Argon JS   -->
    <script src="/static/js/argon-dashboard.min.js?v=1.1.1"></script>
    <script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>

    <!-- BootStrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <!-- BootStrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    {% block style %}{% endblock %}
    <title>{% block title %}Avalya{% endblock %}</title>
</head>
<body>
{% block body %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
{% block script %}{% endblock %}
</html>

apps/core/templates/nav.html
<!-- Navigation -->
<ul class="navbar-nav">
    <li class="nav-item  active ">
        <a class="nav-link " href="{% url 'core:home_view' %}">
            <i class="ni ni-tv-2 text-primary"></i> Dashboard
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link  active " href="{% url 'core:user_profile' %}">
            <i class="ni ni-single-02 text-yellow"></i> User profile
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="{% url 'core:tables_view' %}">
            <i class="ni ni-bullet-list-67 text-red"></i> Tables
        </a>
    </li>
</ul>